apiVersion: v1
kind: Service
metadata:
  name: american-predictor-service
spec:
  selector:
    app: american-predictor-deployment
  ports:
    - protocol: TCP
      port: 5022
      targetPort: 5022

